    name: Python Flake8 Check

    on:
      push:
        branches: [ main, dev ]
      pull_request:
        branches: [ main, dev ]

    jobs:
      flake8-lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3'
        - name: Install dependencies
          run: |
            pip install flake8
        - name: Run Flake8
          run: |
            flake8 . --count --statistics --max-line-length=120 --max-complexity=10